name: Build & Deploy Release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test
        run: mvn -B test

  build:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: mvn -B clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: API
          path: ./target/ziedelth.fr-api-jar-with-dependencies.jar