name: Build & Deploy Release

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Test
        run: mvn -B test

  build:
    runs-on: ubuntu-latest

    needs:
      - test

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build
        run: mvn -B clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: API
          path: ./target/ziedelth.fr-api-jar-with-dependencies.jar

  deploy:
    runs-on: ubuntu-latest

    needs:
      - build

    steps:
      - name: Download all workflow run actifacts
        uses: actions/download-artifact@v2

      - name: Install SSH KEY
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Test SSH
        run: |
          ssh -C ${{ secrets.SSH_DESTINATION }} "echo Editing API at date: `date` >> ~/github-actions.txt"
      - name: SSH Commands
        run: |
          scp API/* ${{ secrets.SSH_DESTINATION }}:${{ secrets.SSH_FOLDER }}/